### ISSUE TITLE
Integram checks webhook, but he not installed..

### ISSUE THREAD

**Issue by kksudo** [requilence/integram#70]
Hi.
I run app in docker-compose. In logs i see check instance webhook, but I did not run and config webhook service. Can i might disable checks this  service ?
Log :
`| 502 |   15.156937ms |   ip_address | GET      /webhook/healthcheck`

Config:
``` 
version: '3'
volumes:
  data-redis: {}
  data-mongo: {}
  data-mainapp: {}
services:
  mongo:
    restart: always
    image: mongo:3.4
    volumes:
      - data-mongo:/data/db
    expose:
      - "27017"
  redis:
    restart: always
    command: redis-server --appendonly yes
    image: redis:3.2
    expose:
        - "6379"
    volumes:
        - data-redis:/data
  integram:
    image: integram/integram:latest
    restart: always
    volumes:
      - data-mainapp:/app/.conf
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - 8085:8085
    environment:
      - TZ=Europe/Moscow
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-main
      - INTEGRAM_CONFIG_DIR=/app/.conf
      ## required ENV vars
      - INTEGRAM_PORT=8085
      - INTEGRAM_BASE_URL=http://tg.domain.net:8080

  gitlab:
    image: integram/gitlab
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - integram
    environment:
      - TZ=Europe/Moscow
      - INTEGRAM_PORT=8085
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=single

      ## required ENV vars
      - INTEGRAM_BASE_URL=http://tg.domain.net:8080
      - GITLAB_BOT_TOKEN=xxx
      - GITLAB_OAUTH_ID=xxx
      - GITLAB_OAUTH_SECRET=xxx
```
