### ISSUE TITLE
Error 504 on gitlab url

### ISSUE THREAD

**Issue by 3kynox** [requilence/integram#73]
Hello there!

I've made an Integram install on a Proxmox LXC (I know it's a container inside a container, I had to modify the Proxmox container configuration in order to do that).

The bot respond correctly on telegram but the web url returned by the bot do not work properly.

1. Gitlab push test hook return -> 
Hook execution failed: Failed to open TCP connection to xxx.xxx.xxx.xxx:8080 (Connection refused - connect(2) for "xxx.xxx.xxx.xxx" port 8080)
2. If I open the returned link on my browser, I get that result ->
Error 504
Connection delay expired
The server abandonned the connection.

Here is my settings:
```
version: '3'
volumes:
  data-redis: {}
  data-mongo: {}
  data-mainapp: {}
services:
  mongo:
    restart: always
    image: mongo:3.4
    volumes:
      - data-mongo:/data/db
    expose:
      - "27017"
  redis:
    restart: always
    command: redis-server --appendonly yes
    image: redis:3.2
    expose:
        - "6379"
    volumes:
        - data-redis:/data
  integram:
    image: integram/integram:latest
    restart: always
    volumes:
      - data-mainapp:/app/.conf
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - 8085:8085
    environment:
      - TZ=UTC
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-main
      - INTEGRAM_CONFIG_DIR=/app/.conf
      ## required ENV vars
      - INTEGRAM_PORT=8085
      - INTEGRAM_BASE_URL=http://xxx.xxx.xxx.xxx:8080
  gitlab:
    image: integram/gitlab
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - integram
    environment:
      - TZ=UTC
      - INTEGRAM_PORT=8085
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-service

      ## required ENV vars
      - INTEGRAM_BASE_URL=http://xxx.xxx.xxx.xxx:8080
      - GITLAB_BOT_TOKEN=xxxxxx
      - GITLAB_OAUTH_ID=xxxxxx
      - GITLAB_OAUTH_SECRET=xxxxxx
(...)
```

Any idea of what's wrong here please ?

Thanks for help!
