### ISSUE TITLE
gitlab healthcheck recursive redirection

### ISSUE THREAD

**Issue by Jeffwhen** [requilence/integram#82]
I am hosting integram  on my own server. GET request to `/gitlab/healthcheck` is recursively redirected to *itself*.

```
version: "3.2"

services:
  mongo:
    image: mongo:3.4
    networks:
      - lab
    volumes:
      - /home/integram/mongo:/data/db

  redis:
    command: redis-server --appendonly yes
    image: redis:3.2
    networks:
      - lab
    volumes:
        - /home/integram/redis:/data

  integram:
    image: integram/integram:alpha
    volumes:
      - /home/integram/mainapp:/app/.conf
    depends_on:
      - mongo
      - redis
    ports:
      - 443:443
    networks:
      - lab
    environment:
      - HTTP_PROXY=http://192.168.2.222:8118
      - http_proxy=http://192.168.2.222:8118
      - TZ=UTC
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-main
      - INTEGRAM_CONFIG_DIR=/app/.conf
      ## required ENV vars
      - INTEGRAM_PORT=443
      - INTEGRAM_BASE_URL=https://registry.yunshitu.cn:443

  gitlab:
    image: integram/gitlab:alpha
    depends_on:
      - integram
    networks:
      - lab
    environment:
      - HTTP_PROXY=http://192.168.2.222:8118
      - http_proxy=http://192.168.2.222:8118
      - TZ=UTC
      - INTEGRAM_PORT=7000
      - INTEGRAM_MONGO_URL=mongodb://mongo:27017/integram
      - INTEGRAM_REDIS_URL=redis:6379
      - INTEGRAM_INSTANCE_MODE=multi-service

      ## required ENV vars
      - INTEGRAM_BASE_URL=http://gitlab:7000
      - GITLAB_BOT_TOKEN="bybottoken"
      - GITLAB_OAUTH_ID="oauthid"
      - GITLAB_OAUTH_SECRET="secret"

networks:
  lab:

```

Also why should i config gitlab oauth in environment variables.
